USE Shrinkr
GO

INSERT [BannedDomain] ([Name]) VALUES('tinyurl.com')
INSERT [BannedDomain] ([Name]) VALUES('bit.ly')
INSERT [BannedDomain] ([Name]) VALUES('j.mp')
INSERT [BannedDomain] ([Name]) VALUES('is.gd')
INSERT [BannedDomain] ([Name]) VALUES('sn.im')
INSERT [BannedDomain] ([Name]) VALUES('u.nu')
INSERT [BannedDomain] ([Name]) VALUES('idek.net')
INSERT [BannedDomain] ([Name]) VALUES('urls.im')
INSERT [BannedDomain] ([Name]) VALUES('k.im')
INSERT [BannedDomain] ([Name]) VALUES('tiny.cc')
INSERT [BannedDomain] ([Name]) VALUES('cli.gs')
INSERT [BannedDomain] ([Name]) VALUES('budurl.com')
INSERT [BannedDomain] ([Name]) VALUES('twurl.nl ')
INSERT [BannedDomain] ([Name]) VALUES('zi.ma')
INSERT [BannedDomain] ([Name]) VALUES('ad.vu')
INSERT [BannedDomain] ([Name]) VALUES('adjix.com')
INSERT [BannedDomain] ([Name]) VALUES('poprl.com')
INSERT [BannedDomain] ([Name]) VALUES('piurl.com')
INSERT [BannedDomain] ([Name]) VALUES('xrl.us')
INSERT [BannedDomain] ([Name]) VALUES('tgr.me')
INSERT [BannedDomain] ([Name]) VALUES('zz.gd')
INSERT [BannedDomain] ([Name]) VALUES('snipurl.com')
INSERT [BannedDomain] ([Name]) VALUES('snurl.com')
INSERT [BannedDomain] ([Name]) VALUES('snipr.com')
INSERT [BannedDomain] ([Name]) VALUES('pnt.me')
INSERT [BannedDomain] ([Name]) VALUES('tr.im')
INSERT [BannedDomain] ([Name]) VALUES('ow.ly')
INSERT [BannedDomain] ([Name]) VALUES('read.ly')
INSERT [BannedDomain] ([Name]) VALUES('ff.im')
INSERT [BannedDomain] ([Name]) VALUES('fb.me')
INSERT [BannedDomain] ([Name]) VALUES('su.pr')
INSERT [BannedDomain] ([Name]) VALUES('digg.com')
INSERT [BannedDomain] ([Name]) VALUES('goo.gl')
INSERT [BannedDomain] ([Name]) VALUES('youtu.be')
INSERT [BannedDomain] ([Name]) VALUES('ping.fm')